browsers = {
""" Type Name : Class Name """
"mozilla" : "Mozilla('mozilla')",
"firefox" : "Mozilla('mozilla')",
"netscape" : "Mozilla('netscape')",
"galeon" : "Galeon('galeon')",
"epiphany" : "Galeon('epiphany')",
"skipstone" : "BackgroundBrowser('skipstone')",
"kfmclient" : "Konqueror()",
"konqueror" : "Konqueror()",
"kfm" : "Konqueror()",
"mosaic" : "BackgroundBrowser('mosaic')",
"opera" : "Opera()",
"grail" : "	Grail()",
"links" : "GenericBrowser('links')",
"elinks" : "Elinks('elinks')",
"lynx" : "GenericBrowser('lynx')",
"w3m" : "GenericBrowser('w3m')",
"windows-default" : "WindowsDefault",
"macosx" : "MacOSX('default')",
"safari" : "MacOSX('safari')",
"google-chrome" : "Chrome('google-chrome')",
"chrome"  : "Chrome('chrome')",
"chromium" : "Chromium('chromium')",
"chromium-browser" : "Chromium('chromium-browser')",
}